#!/usr/bin/env python3
"""
detect_tofu.py — universal "missing glyph" (tofu / .notdef box) detector for
finished PNG/JPG graphics, regardless of which script generated them.

WHY THIS EXISTS
---------------
content/image_maker.py routes emoji to the color-emoji font and strips emoji
from body copy, so the weekly carousel is safe. But ad-hoc one-off assets
(e.g. docs/assets/weekend-preview-bg.png) have historically been generated by
sessions that drew emoji with a plain text font. The font has no glyph for the
codepoint, so it renders the .notdef glyph — a hollow rectangle ("tofu"), often
with an X or a hex code inside. To a human these read as "cheap broken boxes."
Nothing inspected the finished pixels before posting, so they shipped blind.

This detector closes that gap. It looks at the RENDERED PIXELS and flags the
visual signature of tofu: a horizontal RUN of near-identical hollow rectangles
sitting on a shared baseline with uniform spacing. Real text never produces a
run of identical hollow boxes; .notdef glyphs always do.

USAGE
-----
    python tools/detect_tofu.py <image1.png> [<image2.png> ...]
    python tools/detect_tofu.py --json <image.png>
    python tools/detect_tofu.py --selftest      # proves it on known good/bad

Exit code: 0 = all clean, 1 = tofu detected in >=1 image (so it can gate a post).

Public API:
    scan_image(path) -> dict(clean: bool, boxes: int, runs: [...], reason: str)
"""
from __future__ import annotations
import sys
import os
import json
from collections import deque

try:
    from PIL import Image
except Exception as e:  # pragma: no cover
    print("[detect_tofu] Pillow required:", e)
    raise


# ── tunables (empirically set against known good/bad TulsaGays assets) ───────
_MIN_BOX_H_FRAC = 0.012   # a glyph box is at least this fraction of image height
_MAX_BOX_H_FRAC = 0.16    # ...and at most this (anything taller is a panel, not a glyph)
_EDGE_MIN       = 0.85    # min coverage on every bbox edge to call it a box glyph
_MAX_FILL_RATIO = 0.55    # hollow: filled stroke pixels / bbox area must be LOW
_MIN_FILL_RATIO = 0.04    # but not empty noise
_RECT_MIN       = 0.55    # bbox fill of the component's own pixels is rectangular-ish
_RUN_MIN        = 2       # >=2 near-identical boxes in a row = tofu run (the giveaway)
_H_TOL          = 0.18    # box heights within a run agree to this rel. tolerance
_BASELINE_TOL   = 0.45    # vertical centers align within this * median height
_GAP_MAX        = 2.2     # horizontal gap between boxes <= this * box width


def _connected_components(mask, W, H, min_px):
    """8-connected components over a boolean mask. Returns (bbox, count, pixels)."""
    seen = bytearray(W * H)
    comps = []
    for sy in range(H):
        base = sy * W
        for sx in range(W):
            idx = base + sx
            if not mask[idx] or seen[idx]:
                continue
            q = deque([idx])
            seen[idx] = 1
            minx = maxx = sx
            miny = maxy = sy
            pixels = []
            while q:
                c = q.popleft()
                cy, cx = divmod(c, W)
                pixels.append((cx, cy))
                if cx < minx: minx = cx
                if cx > maxx: maxx = cx
                if cy < miny: miny = cy
                if cy > maxy: maxy = cy
                for dy in (-1, 0, 1):
                    ny = cy + dy
                    if ny < 0 or ny >= H:
                        continue
                    for dx in (-1, 0, 1):
                        if dx == 0 and dy == 0:
                            continue
                        nx = cx + dx
                        if nx < 0 or nx >= W:
                            continue
                        nidx = ny * W + nx
                        if mask[nidx] and not seen[nidx]:
                            seen[nidx] = 1
                            q.append(nidx)
            if len(pixels) >= min_px:
                comps.append(((minx, miny, maxx, maxy), len(pixels), pixels))
    return comps


def _is_box_glyph(bbox, pixels):
    """
    Structural test for a .notdef "tofu" box. The defining signature is a stroke
    that runs along ALL FOUR edges of the bounding box with the corners filled —
    a closed rectangle. Letters almost never satisfy this: H/E/F/T have an open
    edge, I is a bar, and O/C/G/S have rounded (empty) corners. This holds whether
    the box is hollow OR carries an inner X/hex code, so it catches both kinds.
    Returns (is_box, score).
    """
    x0, y0, x1, y1 = bbox
    bw = x1 - x0 + 1
    bh = y1 - y0 + 1
    if bw < 4 or bh < 6:
        return False, 0.0
    # local grid
    grid = [[False] * bw for _ in range(bh)]
    for (cx, cy) in pixels:
        grid[cy - y0][cx - x0] = True

    band = max(1, int(round(min(bw, bh) * 0.18)))   # edge band thickness

    def col_has(x, y_lo, y_hi):
        for yy in range(y_lo, y_hi):
            if grid[yy][x]:
                return True
        return False

    def row_has(y, x_lo, x_hi):
        row = grid[y]
        for xx in range(x_lo, x_hi):
            if row[xx]:
                return True
        return False

    # edge coverage: fraction of the edge spanned by stroke pixels in its band
    top_cov = sum(1 for x in range(bw) if row_has_band(grid, range(0, band), x)) / bw
    bot_cov = sum(1 for x in range(bw) if row_has_band(grid, range(bh - band, bh), x)) / bw
    left_cov = sum(1 for y in range(bh) if col_has_band(grid, range(0, band), y)) / bh
    right_cov = sum(1 for y in range(bh) if col_has_band(grid, range(bw - band, bw), y)) / bh
    edge_min = min(top_cov, bot_cov, left_cov, right_cov)

    # corners filled (distinguishes a rectangle from a rounded O/Q/C)
    cz = max(2, int(round(min(bw, bh) * 0.22)))
    corners = [
        any(grid[y][x] for y in range(0, cz) for x in range(0, cz)),                       # TL
        any(grid[y][x] for y in range(0, cz) for x in range(bw - cz, bw)),                 # TR
        any(grid[y][x] for y in range(bh - cz, bh) for x in range(0, cz)),                 # BL
        any(grid[y][x] for y in range(bh - cz, bh) for x in range(bw - cz, bw)),           # BR
    ]
    corners_ok = sum(corners)

    # A true .notdef box has near-complete coverage on all four edges AND all
    # four corners filled. Letters that survive the geometry pre-filter top out
    # around 0.75 edge coverage (a closed 'o'/'a' serif clipping a corner), so a
    # high threshold cleanly separates real tofu (~1.0) from text.
    is_box = edge_min >= _EDGE_MIN and corners_ok == 4
    score = edge_min if is_box else 0.0
    return is_box, score


def row_has_band(grid, yrange, x):
    for yy in yrange:
        if grid[yy][x]:
            return True
    return False


def col_has_band(grid, xrange, y):
    row = grid[y]
    for xx in xrange:
        if row[xx]:
            return True
    return False


def _box_candidates(img):
    """Return .notdef box-glyph candidates as (x0,y0,x1,y1,score)."""
    W, H = img.size
    scale = 1.0
    if max(W, H) > 900:
        scale = 900.0 / max(W, H)
        img = img.resize((max(1, int(W * scale)), max(1, int(H * scale))))
        W, H = img.size

    gray = img.convert("L")
    px = list(gray.getdata())
    mean = sum(px) / len(px)
    light_mask = [p > mean + 35 for p in px]   # bright strokes on dark bg
    dark_mask = [p < mean - 35 for p in px]    # dark strokes on light bg

    # Absolute floor (14px scaled ~= 17px in a 1080 image) plus the fractional one
    # cuts small body-text glyphs (an 'i'/'l'/':' can pass the box geometry but is
    # too small to read as a broken box) while keeping real tofu (h>=24px scaled).
    min_h = max(14, int(_MIN_BOX_H_FRAC * H))
    max_h = int(_MAX_BOX_H_FRAC * H)
    min_px = max(10, int(min_h * 0.8))

    best = []
    for mask in (light_mask, dark_mask):
        comps = _connected_components(mask, W, H, min_px)
        cands = []
        for (bbox, count, pixels) in comps:
            x0, y0, x1, y1 = bbox
            bw = x1 - x0 + 1
            bh = y1 - y0 + 1
            if bh < min_h or bh > max_h:
                continue
            if bw < 8 or bw < bh * 0.45 or bw > bh * 1.6:   # box aspect band + abs floor
                continue
            is_box, score = _is_box_glyph(bbox, pixels)
            if is_box:
                cands.append((x0, y0, x1, y1, score))
        if len(cands) > len(best):
            best = cands
    return best, scale


def _find_runs(cands):
    """Group candidates into baseline-aligned, uniform-height, evenly-spaced runs."""
    if len(cands) < _RUN_MIN:
        return []
    # sort left to right
    items = sorted(cands, key=lambda c: c[0])
    runs = []
    used = [False] * len(items)
    for i in range(len(items)):
        if used[i]:
            continue
        x0, y0, x1, y1, f = items[i]
        h = y1 - y0 + 1
        cy = (y0 + y1) / 2
        w = x1 - x0 + 1
        run = [items[i]]
        used[i] = True
        last = items[i]
        for j in range(i + 1, len(items)):
            if used[j]:
                continue
            jx0, jy0, jx1, jy1, jf = items[j]
            jh = jy1 - jy0 + 1
            jcy = (jy0 + jy1) / 2
            # height agreement
            if abs(jh - h) > _H_TOL * max(h, jh):
                continue
            # baseline agreement
            if abs(jcy - cy) > _BASELINE_TOL * h:
                continue
            # horizontal proximity to previous box in the run
            gap = jx0 - last[2]
            if gap < -2 or gap > _GAP_MAX * w:
                continue
            run.append(items[j])
            used[j] = True
            last = items[j]
        if len(run) >= _RUN_MIN:
            rx0 = min(b[0] for b in run); ry0 = min(b[1] for b in run)
            rx1 = max(b[2] for b in run); ry1 = max(b[3] for b in run)
            runs.append({"count": len(run), "bbox": [rx0, ry0, rx1, ry1]})
    return runs


def scan_image(path: str) -> dict:
    """Return a verdict dict for one image."""
    if not os.path.exists(path):
        return {"clean": False, "boxes": 0, "runs": [], "reason": f"missing file: {path}", "path": path}
    try:
        img = Image.open(path)
        img.load()
    except Exception as e:
        return {"clean": False, "boxes": 0, "runs": [], "reason": f"unreadable: {e}", "path": path}

    cands, scale = _box_candidates(img)
    runs = _find_runs(cands)
    box_total = sum(r["count"] for r in runs)
    clean = len(runs) == 0
    reason = "clean" if clean else (
        f"{len(runs)} tofu run(s), {box_total} missing-glyph boxes "
        f"(uniform hollow rectangles on a shared baseline)"
    )
    return {"clean": clean, "boxes": box_total, "runs": runs, "reason": reason, "path": path}


def _selftest() -> int:
    """Prove discrimination on known assets if present; else synthesize."""
    import io
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # Permanent known-bad fixture: the EXACT tofu image that posted to IG on
    # 2026-06-20 (saved so this can never regress to a falsely-clean reference;
    # docs/assets/weekend-preview-bg.png was rebuilt clean, so it is no longer bad).
    bad = os.path.join(root, "tests", "fixtures", "tofu_weekend_live.png")
    if not os.path.exists(bad):  # fallback to the live asset path if fixture absent
        bad = os.path.join(root, "docs", "assets", "weekend-preview-bg.png")
    good_dir = os.path.join(root, "data", "posts", "2026-W25")
    goods = []
    if os.path.isdir(good_dir):
        for f in sorted(os.listdir(good_dir)):
            if f.startswith("all__") and f.endswith(".png"):
                goods.append(os.path.join(good_dir, f))
    ok = True
    if os.path.exists(bad):
        v = scan_image(bad)
        flagged = not v["clean"]
        print(f"[selftest] KNOWN-BAD {os.path.basename(bad)} -> "
              f"{'FLAGGED OK' if flagged else 'MISSED FAIL'} ({v['reason']})")
        ok = ok and flagged
    for g in goods[:4]:
        v = scan_image(g)
        passed = v["clean"]
        print(f"[selftest] KNOWN-GOOD {os.path.basename(g)} -> "
              f"{'PASS OK' if passed else 'FALSE-POS FAIL'} ({v['reason']})")
        ok = ok and passed

    # Synthetic guarantee: render real tofu and a clean line, prove both ways.
    from PIL import ImageDraw, ImageFont
    win = os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "Fonts")
    plain_path = os.path.join(win, "segoeui.ttf")
    if os.path.exists(plain_path):
        # Realistic Instagram-square canvas so the height filter behaves as in prod.
        plain = ImageFont.truetype(plain_path, 70)
        im = Image.new("RGB", (1080, 1080), (15, 15, 40))
        d = ImageDraw.Draw(im)
        # Emoji codepoints in a NON-emoji font => guaranteed .notdef boxes
        d.text((120, 480), "\U0001F308\U00002728\U0001F3F3 TulsaGays \U00002728\U0001F308",
               font=plain, fill=(240, 220, 80))
        v = scan_image_from(im)
        print(f"[selftest] SYNTHETIC tofu line -> "
              f"{'FLAGGED OK' if not v['clean'] else 'MISSED FAIL'} ({v['reason']})")
        ok = ok and (not v["clean"])

        im2 = Image.new("RGB", (1080, 1080), (15, 15, 40))
        d2 = ImageDraw.Draw(im2)
        d2.text((120, 480), "This Weekend in Tulsa", font=plain, fill=(255, 255, 255))
        v2 = scan_image_from(im2)
        print(f"[selftest] SYNTHETIC clean line -> "
              f"{'PASS OK' if v2['clean'] else 'FALSE-POS FAIL'} ({v2['reason']})")
        ok = ok and v2["clean"]

    print("[selftest]", "ALL PASS" if ok else "FAILURES PRESENT")
    return 0 if ok else 1


def scan_image_from(img) -> dict:
    """scan_image variant for an in-memory PIL image (used by selftest)."""
    cands, scale = _box_candidates(img)
    runs = _find_runs(cands)
    box_total = sum(r["count"] for r in runs)
    clean = len(runs) == 0
    reason = "clean" if clean else f"{len(runs)} tofu run(s), {box_total} boxes"
    return {"clean": clean, "boxes": box_total, "runs": runs, "reason": reason, "path": "<memory>"}


def main(argv):
    args = [a for a in argv if not a.startswith("--")]
    flags = {a for a in argv if a.startswith("--")}
    if "--selftest" in flags:
        return _selftest()
    if not args:
        print(__doc__.strip())
        return 2
    results = [scan_image(p) for p in args]
    if "--json" in flags:
        print(json.dumps(results, indent=2))
    else:
        for r in results:
            tag = "CLEAN" if r["clean"] else "TOFU"
            print(f"[{tag}] {os.path.basename(r['path'])}: {r['reason']}")
    return 0 if all(r["clean"] for r in results) else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
