#!/usr/bin/env python3
"""
gen_weekend_preview_bg.py — regenerate docs/assets/weekend-preview-bg.png cleanly.

The old asset was generated by an ad-hoc session that drew emoji with a plain
(non-emoji) font, baking ".notdef" tofu boxes around "TulsaGays.com" on a muddy
full-bleed rainbow. This rebuild is on-brand (near-black bg, neon-pink accent,
white headline) with a CRISP vector rainbow accent (no emoji-font dependency at
all) plus one color emoji routed through the real emoji font. The output is
verified by tools/detect_tofu.py before it can replace the live asset.
"""
from __future__ import annotations
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "tools"))

from PIL import Image, ImageDraw  # noqa: E402
from content.image_maker import _font, BG, NEON_PINK, WHITE  # noqa: E402
import detect_tofu  # noqa: E402

OUT = os.path.join(ROOT, "docs", "assets", "weekend-preview-bg.png")
SIZE = (1080, 1080)

# Vivid, saturated pride spectrum (the old asset's stripes were desaturated/muddy)
RAINBOW = [
    (228, 3, 3),     # red
    (255, 140, 0),   # orange
    (255, 237, 0),   # yellow
    (0, 128, 38),    # green
    (0, 77, 255),    # blue
    (117, 7, 135),   # violet
]
GOLD = (255, 209, 102)


def _text_w(draw, text, font):
    b = draw.textbbox((0, 0), text, font=font)
    return b[2] - b[0]


def _centered(draw, text, y, font, fill):
    w = _text_w(draw, text, font)
    draw.text(((SIZE[0] - w) // 2, y), text, font=font, fill=fill)
    b = draw.textbbox((0, 0), text, font=font)
    return y + (b[3] - b[1]) + (b[1])  # advance roughly by glyph height


def build() -> Image.Image:
    W, H = SIZE
    img = Image.new("RGB", SIZE, BG)
    d = ImageDraw.Draw(img)

    # ── crisp rainbow accent bands (vector, top + bottom) ──
    band_h = 26
    seg = W // len(RAINBOW)
    for i, col in enumerate(RAINBOW):
        x0 = i * seg
        x1 = W if i == len(RAINBOW) - 1 else (i + 1) * seg
        d.rectangle([x0, 0, x1, band_h], fill=col)
        d.rectangle([x0, H - band_h, x1, H], fill=col)

    # ── headline ──
    f_head = _font("segoe-bold", 132)
    f_sub = _font("segoe-bold", 132)
    y = 372
    _centered(d, "THIS WEEKEND", y, f_head, WHITE)
    _centered(d, "IN TULSA", y + 150, f_sub, WHITE)

    # ── neon-pink accent rule ──
    rule_w = 360
    ry = y + 312
    d.rectangle([(W - rule_w) // 2, ry, (W + rule_w) // 2, ry + 8], fill=NEON_PINK)

    # ── domain line (gold), flanked by a properly-rendered color emoji ──
    f_dom = _font("segoe-bold", 60)
    f_emoji = _font("segoe-emoji", 56)
    domain = "TULSAGAYS.COM"
    star = "✨"  # ✨ rendered via the COLOR emoji font, embedded_color=True
    gap = 26
    dom_w = _text_w(d, domain, f_dom)
    em_w = _text_w(d, star, f_emoji)
    total = em_w + gap + dom_w + gap + em_w
    dx = (W - total) // 2
    dy = ry + 70
    # left emoji
    d.text((dx, dy - 2), star, font=f_emoji, fill=GOLD, embedded_color=True)
    # domain
    d.text((dx + em_w + gap, dy), domain, font=f_dom, fill=GOLD)
    # right emoji
    d.text((dx + em_w + gap + dom_w + gap, dy - 2), star, font=f_emoji, fill=GOLD,
           embedded_color=True)

    return img


def main():
    img = build()
    tmp = OUT + ".tmp.png"
    img.save(tmp)

    # HARD GATE: do not replace the live asset unless it is tofu-clean.
    verdict = detect_tofu.scan_image(tmp)
    if not verdict["clean"]:
        os.remove(tmp)
        print(f"[FAIL] regenerated asset still has tofu: {verdict['reason']}")
        return 1
    os.replace(tmp, OUT)
    print(f"[OK] wrote {OUT} — tofu-clean ({verdict['reason']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
